### Single
# Hauptauftrag Neukunde mit Kontoanlage und Unterschriftenverzeichnis
POST http://localhost:8099/clmdirect/hauptauftrag/start
Content-Type: application/json

{
  "kundenPayload": {
    "kundenName": "Kunde1"
  },
  "kontoPayloads": [
    {
      "kontoName": "konto1"
    }
  ],
  "uvzPayloads": [
    {
      "uvzName": "uvz1",
      "kontoName": "konto1"
    }
  ]
}

### Single V2
POST http://localhost:8099/clmdirect/hauptauftrag/startV2
Content-Type: application/json