### Extras
### Kundenanlage
@businessKey = 49a73523-9195-4168-81d2-c84f0b1eeb55

### Kontoanlage
POST http://localhost:8099/clmdirect/hauptauftrag/kontoanlage/{{businessKey}}
Content-Type: application/json

{
  "kontoName": "extraKonto1"
}

### Kundenanlage
POST http://localhost:8099/clmdirect/hauptauftrag/kundenanlage/{{businessKey}}
Content-Type: application/json

{
  "kundenName": "Kunde1"
}

### UVZanlage
POST http://localhost:8099/clmdirect/hauptauftrag/uvzanlage/{{businessKey}}
Content-Type: application/json

{
  "uvzName": "uvz2"
}

### Hauptauftragprozess stoppen
POST http://localhost:8099/clmdirect/hauptauftrag/stopV2/{{businessKey}}
Content-Type: application/json